version: '3.8'
services:
  db:
    image: postgres:14.4
    container_name: currency_tracker_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=currency_tracker_db
    volumes:
      - currency_tracker_db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  currency_tracker_db:
    driver: local